import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from '../styles/styles.module.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Emmanuel MetaData",
  description: "Generated by Vercel",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <div className={styles['global-styles']}>
        {children}
    </div>
    </html>
  );
}
